#
# DigitalOcean App Platform Spec for PocketBase
#
# This configuration deploys PocketBase with ephemeral SQLite storage.
# For production use, configure Litestream to backup SQLite to DigitalOcean Spaces.
# See README.md for Litestream setup instructions.
#
name: pocketbase
region: nyc

services:
  - name: pocketbase
    # Source configuration
    github:
      repo: AppPlatform-Templates/pocketbase-appplatform
      branch: main
      deploy_on_push: true

    # Build configuration
    dockerfile_path: Dockerfile

    # Optional: Override PocketBase version (default: v0.31.0)
    # Uncomment to build a different version:
    # build_command: docker build --build-arg POCKETBASE_VERSION=v0.32.0 -t $IMAGE_NAME .

    # Instance configuration
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-1gb

    # HTTP configuration
    http_port: 8080

    # Health check
    health_check:
      http_path: /api/health
      initial_delay_seconds: 10
      period_seconds: 10
      timeout_seconds: 3
      success_threshold: 1
      failure_threshold: 3

    # Environment variables
    envs:
      - key: PB_LOG_LEVEL
        value: "info"
        scope: RUN_TIME

      # Litestream configuration (optional - for production backups)
      # Uncomment and configure these to enable automatic SQLite backups to DigitalOcean Spaces
      # See README.md for setup instructions

      # - key: LITESTREAM_ACCESS_KEY_ID
      #   value: "your-spaces-access-key-id"
      #   scope: RUN_TIME
      #   type: SECRET

      # - key: LITESTREAM_SECRET_ACCESS_KEY
      #   value: "your-spaces-secret-access-key"
      #   scope: RUN_TIME
      #   type: SECRET

      # - key: REPLICA_URL
      #   value: "s3://your-space-name.nyc3.digitaloceanspaces.com/pocketbase-db"
      #   scope: RUN_TIME

    # Routes
    routes:
      - path: /

    # CORS configuration (optional - uncomment if needed)
    # cors:
    #   allow_origins:
    #     - prefix: "*"
    #   allow_methods:
    #     - GET
    #     - POST
    #     - PUT
    #     - PATCH
    #     - DELETE
    #     - OPTIONS
    #   allow_headers:
    #     - "*"

# Notes:
# 1. SQLite storage is EPHEMERAL - data will be lost on each deployment without backups
# 2. For production, configure Litestream to backup to DigitalOcean Spaces (see README.md)
# 3. Maximum 2GiB local storage available
# 4. Database file location: /app/pb_data/data.db
# 5. PocketBase only supports SQLite (PostgreSQL is NOT supported)
